version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ads}
      MYSQL_USER: ${MYSQL_USER:-ads}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-ads_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
